### ISSUE TITLE
Implement AE 8.4.0-beta support

### ISSUE THREAD

**Issue by sgdc3** [Tfarcenim/AE2WirelessTerminalLibrary#12]
A new branch should be started in order to prepare for 8.4.0 AE API changes

**Comment by Tfarcenim** [comment]
No, it will only be done when it's at least beta or stable, I simply don't have the time to track every version.

**Comment by Larandar** [comment]
Can this issue can be reopened now that 8.4 is in beta and quite stable?

**Comment by Tfarcenim** [comment]
better

**Comment by Fireztonez** [comment]
I don't know if this can be usefull for you, but here's my crashlog when I try to start with the latest current release from AE2 (v.8.4.0):
https://gist.github.com/Fireztonez/75fe5ba5ed71d30ec83970b90952f35a
