### ISSUE TITLE
JEI won't place recipe item in the Wireless Crafting Terminal

### ISSUE THREAD

**Issue by frank89722** [Tfarcenim/AE2WirelessTerminalLibrary#17]
As title
JEI-7.7.0.104
ae2wtlib-0.2-1.16.5
![wct](https://user-images.githubusercontent.com/10683361/120932754-a6259700-c729-11eb-9949-3e7cf3c1e03d.gif)

**Comment by d3leet3d** [comment]
I have the same issue.

**Comment by Tannelol** [comment]
also having this issue, seems to be something everyone is affected by

**Comment by LoneStarrr** [comment]
Indeed still the case - and I can see now why. AE2 did a major rewrite from 0.8.3 to 0.8.4 for the UI parts. Porting those changes is a lot of work, it needs a significant refactor for this mod as well.

**Comment by Gillios** [comment]
Unfortunately it still doesn't work. You can't craft with Jei

**Comment by FearAK** [comment]
Doesn't work for me either, using the latest update :(

**Comment by ElizaYamamoto** [comment]
This is still an issue. Please fix soon ;-;

**Comment by frank89722** [comment]
Still happen in 0.3.3
