### ISSUE TITLE
The wireless crafting terminal is able to replicate items in certain condition

### ISSUE THREAD

**Issue by ZHENGLOC** [Tfarcenim/AE2WirelessTerminalLibrary#19]
While the terminal GUI is open, attempting to use the sort inventory feature of invtweaks causes items in the crafting grid, trash slot and the two upgrade slots to duplicate, as the screenshot shown below

version:
invtweaks-1.16.4-1.0.1
ae2wtlib-0.2-1.16.5
appliedenergistics2-8.3.1
forge36.1.16

![QQ截图2021060809381125](https://user-images.githubusercontent.com/24859848/121112509-16740b80-c843-11eb-84f8-54a1e77029cb.png)

**Comment by Tfarcenim** [comment]
Wonderful, that mod creates nothing but problems for guis, try blacklisting it.

**Comment by ZHENGLOC** [comment]
> Wonderful, that mod creates nothing but problems for guis, try blacklisting it.

thanks , the blacklist can work.
