### ISSUE TITLE
Game crash during load_registries event phase

### ISSUE THREAD

**Issue by Jabele10** [Tfarcenim/AE2WirelessTerminalLibrary#2]
When starting the game it crashes. It seems like a class is missing. Crash report:
[crash-2021-05-20_12.18.20-fml.txt](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/files/6515061/crash-2021-05-20_12.18.20-fml.txt)

**Comment by Jabele10** [comment]
After a lot of time I finally figured it out. The mod is working fine when using the current stable release of AE2. By using the current alpha (8.4.0-alpha.2) of AE2 it crashes. It says that it's an error of this mod while it is actually an error of compatibility between this mod and the alpha of AE2.

**Comment by Tfarcenim** [comment]
I'll wait until stable/beta is released then, I don't feel like compiling against an alpha only for it to break a week later

**Comment by marc-cwm** [comment]
Can you give us a bit more info about what version we expect to work?  I'm getting what appears to be the same error on version 8.3.1 which seems to be the current 'release' version.

**Comment by Tfarcenim** [comment]
that might explain it, I was running8.2.0 stable
I'll bump it to 8.3.1
