### ISSUE TITLE
Mod incompatile with newest AE2 Version

### ISSUE THREAD

**Issue by Chaosdave34** [Tfarcenim/AE2WirelessTerminalLibrary#22]
The Mod seems incompatile with newest AE2 Version (I think from beginning june). Will there be an update to fix it?

**Comment by SilverScreamBr** [comment]
Please update this on curse

**Comment by Tfarcenim** [comment]
Duplicate of #16, it will be updated when I have the time, but unfortunately paid work comes first as I still have bills.
