### ISSUE TITLE
Can't play in Lan (With Hamachi)

### ISSUE THREAD

**Issue by Lacsaysy** [Tfarcenim/AE2WirelessTerminalLibrary#23]
When I try to join to my Friend's world with Hamachi Its says: failed to synchronize registry data from server closing connection.
What can I do?

**Comment by Tfarcenim** [comment]
Start  by posting a log from both sides

**Comment by Lacsaysy** [comment]
![Screenshot016](https://user-images.githubusercontent.com/87574372/126075623-1726a10e-e6e6-4063-ad74-55156ca4b2ea.PNG)
This is my side. But i can't show the other because my friend is on vacation. But the thing is that he can join to his SinglePlayer world open to lan he give me the Port and this scrren shows up to me. (sry for bad English)

**Comment by Tfarcenim** [comment]
I can't help from a screenshot, I need an actual log (latest.log or debug.log)

**Comment by Lacsaysy** [comment]
[latestlog.txt](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/files/6836639/latestlog.txt)
I think this is the log what i have to share. (I edited out my Friends ip and my name)

**Comment by Tfarcenim** [comment]
The AE2 versions need to be the same on both sides

**Comment by Tfarcenim** [comment]
Since this isn't an issue with Wireless Terminals, I will be closing.
