### ISSUE TITLE
Autocrafting Corruption

### ISSUE THREAD

**Issue by DoktorAerzt** [Tfarcenim/AE2WirelessTerminalLibrary#27]
When you have the mod installed you can´t use the autocrafting correct. 

Every time you try to craft something you can set the amount but when you press start the window stays open but the crafting process is started. Also when you have more than one crafting cpu the crafting process is started on evry cpu. 

Hope you understand the problem.

**Comment by lephro** [comment]
Yeah I can confirm this. On our server each crafting request will get send twice. The first crafting job run normal, the second most often just stops. Im happy to provide any information that might help to fix the issue.

**Comment by rafaelg300** [comment]
tem algum jeito de corrigir esse bug?

**Comment by rafaelg300** [comment]
is there any way to fix this bug?

**Comment by lephro** [comment]
There certainly is, but the problem is, that none of us appearently nows the way. But iam sure its fixable ;)

**Comment by thakyZ** [comment]
The problem with the window staying open when you press "start" is also a bug with regular AE2 so it's probably not a bug with the Wireless Terminal Library specifically

**Comment by Mari023** [comment]
> The problem with the window staying open when you press "start" is also a bug with regular AE2 so it's probably not a bug with the Wireless Terminal Library specifically

It only happens if this mod is installed tho

**Comment by zoller27osu** [comment]
In my experience, it either doesn't close, or crafts more than you asked for, but not usually both.
It also leaves phantom crafting tasks inside of CPUs that will never complete and have to be tracked down and cancelled.

**Comment by Peca21** [comment]
Same
https://streamable.com/xruk3r
Can someone publish the fix from PRs?

**Comment by TainanRezende** [comment]
> Same https://streamable.com/xruk3r Can someone publish the fix from PRs?

I went to try to help the mod developer and that's what I got
![Captura de tela 2021-12-29 072742](https://user-images.githubusercontent.com/86209504/147652739-dc97d84b-3b83-4290-95f9-9a97e7cf1430.png)

**Comment by Peca21** [comment]
CooI fixed it and compiled it myself, but its still buggy as hell

**Comment by Tfarcenim** [comment]
And now you know why I won't publish individual PRs as a release.  Thanks for coming to my Ted talk.

**Comment by Peca21** [comment]
Cool can you actually fix it then? Or do I have to learn forge modding to fix it?

**Comment by Tfarcenim** [comment]
I will fix it when I feel like it, at the moment I have higher priorities.

If you do not pay for my labor or help in other ways, you do not get any priority or have any rights.

I don't really care if you learn forge modding and fix it yourself, but like I said, I do not support 3rd party builds.

**Comment by Peca21** [comment]
Ok, no problem. I just wanted to know if you are busy or not.

**Comment by aaronhowser1** [comment]
Will this ever be uploaded to CF?

**Comment by Tfarcenim** [comment]
I have it fixed in dev, but I'm trying to fix an issue where the terminal switches back to the wrong screen after sending a craft request, otherwise this would be out already.
