### ISSUE TITLE
Wireless Pattern Terminal crashes the game

### ISSUE THREAD

**Issue by Jabele10** [Tfarcenim/AE2WirelessTerminalLibrary#3]
When opening a Wireless Pattern Terminal the game just crashes. Only happens with the Pattern Terminal, others work. Crash report: [crash-2021-05-20_14.51.38-server.txt](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/files/6516021/crash-2021-05-20_14.51.38-server.txt)

**Comment by Tfarcenim** [comment]
does 0.0c fix this?

**Comment by Jabele10** [comment]
Yep, Pattern Terminal is working great.
