### ISSUE TITLE
Magnet Card does not work

### ISSUE THREAD

**Issue by Jabele10** [Tfarcenim/AE2WirelessTerminalLibrary#5]
When putting the Magnet Card in the Wireless Crafting Terminal nothing happens. Items laying around are not attracted and just go into inventory normally. There is also no key to activate it and key combinations are also not activating it. As README.md (should be updated to this mod and not the fabric one) says, it has also no filtering which is expected.

**Comment by Tfarcenim** [comment]
fixed in 0.1
